export default function handler(req, res) {
  const { model } = req.query;

  if (!model) {
    return res.status(400).json({
      data: [],
      message: "Model parameter is required",
      hasError: true,
      errorDataCollection: ["Missing model parameter"],
      statusCode: 400
    });
  }

  // Dados completos da Apple
  const appleDevices = [
    { IdObjectSmartphone: 1024, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1027, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO MAX", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1156, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1159, DeFamilyModel: "IPHONE AIR", DeModel: "IPHONE AIR", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1162, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO MAX", DeMemory: "1 TB" },
    { IdObjectSmartphone: 239, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 243, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO MAX", DeMemory: "1 TB" },
    { IdObjectSmartphone: 341, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 345, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO MAX", DeMemory: "1 TB" },
    { IdObjectSmartphone: 467, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 470, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO MAX", DeMemory: "1 TB" },
    { IdObjectSmartphone: 337, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PLUS", DeMemory: "128 GB" },
    { IdObjectSmartphone: 342, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO MAX", DeMemory: "128 GB" },
    { IdObjectSmartphone: 461, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PLUS", DeMemory: "128 GB" },
    { IdObjectSmartphone: 464, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 471, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1015, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1018, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PLUS", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1021, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1084, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16E", DeMemory: "128 GB" },
    { IdObjectSmartphone: 212, DeFamilyModel: "IPHONE 11", DeModel: "IPHONE 11", DeMemory: "128 GB" },
    { IdObjectSmartphone: 220, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12", DeMemory: "128 GB" },
    { IdObjectSmartphone: 223, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 MINI", DeMemory: "128 GB" },
    { IdObjectSmartphone: 226, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 229, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO MAX", DeMemory: "128 GB" },
    { IdObjectSmartphone: 232, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13", DeMemory: "128 GB" },
    { IdObjectSmartphone: 235, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 MINI", DeMemory: "128 GB" },
    { IdObjectSmartphone: 238, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 242, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO MAX", DeMemory: "128 GB" },
    { IdObjectSmartphone: 332, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14", DeMemory: "128 GB" },
    { IdObjectSmartphone: 334, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1163, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO MAX", DeMemory: "2 TB" },
    { IdObjectSmartphone: 221, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12", DeMemory: "256 GB" },
    { IdObjectSmartphone: 224, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 MINI", DeMemory: "256 GB" },
    { IdObjectSmartphone: 227, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 230, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 233, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13", DeMemory: "256 GB" },
    { IdObjectSmartphone: 236, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 MINI", DeMemory: "256 GB" },
    { IdObjectSmartphone: 240, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 244, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 331, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14", DeMemory: "256 GB" },
    { IdObjectSmartphone: 338, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 340, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 343, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 462, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 465, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 468, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 472, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1016, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1019, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1022, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1025, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1085, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16E", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1152, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1154, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1157, DeFamilyModel: "IPHONE AIR", DeModel: "IPHONE AIR", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1160, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO MAX", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1153, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1155, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1158, DeFamilyModel: "IPHONE AIR", DeModel: "IPHONE AIR", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1161, DeFamilyModel: "IPHONE 17", DeModel: "IPHONE 17 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 228, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 231, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 234, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13", DeMemory: "512 GB" },
    { IdObjectSmartphone: 237, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 MINI", DeMemory: "512 GB" },
    { IdObjectSmartphone: 241, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 245, DeFamilyModel: "IPHONE 13", DeModel: "IPHONE 13 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 308, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12", DeMemory: "512 GB" },
    { IdObjectSmartphone: 333, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14", DeMemory: "512 GB" },
    { IdObjectSmartphone: 336, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 339, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 344, DeFamilyModel: "IPHONE 14", DeModel: "IPHONE 14 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 460, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15", DeMemory: "512 GB" },
    { IdObjectSmartphone: 463, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 469, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 473, DeFamilyModel: "IPHONE 15", DeModel: "IPHONE 15 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1017, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1020, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1023, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1026, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16 PRO MAX", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1086, DeFamilyModel: "IPHONE 16", DeModel: "IPHONE 16E", DeMemory: "512 GB" },
    { IdObjectSmartphone: 222, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12", DeMemory: "64 GB" },
    { IdObjectSmartphone: 225, DeFamilyModel: "IPHONE 12", DeModel: "IPHONE 12 MINI", DeMemory: "64 GB" }
  ];

  // Dados completos da Motorola
  const motorolaDevices = [
    { IdObjectSmartphone: 1129, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 60 ULTRA", DeMemory: "1 TB" },
    { IdObjectSmartphone: 405, DeFamilyModel: "MOTO G", DeModel: "MOTO G53", DeMemory: "128 GB" },
    { IdObjectSmartphone: 429, DeFamilyModel: "MOTO G", DeModel: "MOTO G73", DeMemory: "128 GB" },
    { IdObjectSmartphone: 487, DeFamilyModel: "MOTO G", DeModel: "MOTO G54", DeMemory: "128 GB" },
    { IdObjectSmartphone: 954, DeFamilyModel: "MOTO G", DeModel: "MOTO G34", DeMemory: "128 GB" },
    { IdObjectSmartphone: 970, DeFamilyModel: "MOTO G", DeModel: "MOTO G24 POWER", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1069, DeFamilyModel: "MOTO G", DeModel: "MOTO G35", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1071, DeFamilyModel: "MOTO G", DeModel: "MOTO G05", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1134, DeFamilyModel: "MOTO G", DeModel: "MOTO G15", DeMemory: "128 GB" },
    { IdObjectSmartphone: 17, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 30", DeMemory: "256 GB" },
    { IdObjectSmartphone: 18, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 30 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 353, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 30 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 428, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 30 FUSION", DeMemory: "256 GB" },
    { IdObjectSmartphone: 474, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 40", DeMemory: "256 GB" },
    { IdObjectSmartphone: 486, DeFamilyModel: "MOTO G", DeModel: "MOTO G84", DeMemory: "256 GB" },
    { IdObjectSmartphone: 489, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 40 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 542, DeFamilyModel: "MOTO G", DeModel: "MOTO G54", DeMemory: "256 GB" },
    { IdObjectSmartphone: 543, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 40 NEO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 585, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 50 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 586, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 50 FUSION", DeMemory: "256 GB" },
    { IdObjectSmartphone: 588, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 40", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1008, DeFamilyModel: "MOTO G", DeModel: "MOTO G34", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1028, DeFamilyModel: "MOTO G", DeModel: "MOTO G85", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1029, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 50", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1030, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 50 NEO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1038, DeFamilyModel: "MOTO G", DeModel: "MOTO G55", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1051, DeFamilyModel: "MOTO G", DeModel: "MOTO G24", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1052, DeFamilyModel: "MOTO G", DeModel: "MOTO G75", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1059, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 30 NEO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1070, DeFamilyModel: "MOTO G", DeModel: "MOTO G35", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1072, DeFamilyModel: "MOTO G", DeModel: "MOTO G15", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1105, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 60 FUSION", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1128, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 60", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1131, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 60 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1135, DeFamilyModel: "MOTO G", DeModel: "MOTO G56", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1138, DeFamilyModel: "MOTO G", DeModel: "MOTO G86", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1123, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 60", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1130, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 60 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 978, DeFamilyModel: "MOTO EDGE", DeModel: "MOTO EDGE 50 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1007, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 50 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1103, DeFamilyModel: "MOTO RAZR", DeModel: "MOTO RAZR 50", DeMemory: "512 GB" }
  ];

  // Dados completos da Xiaomi
  const xiaomiDevices = [
    { IdObjectSmartphone: 578, DeFamilyModel: "REDMI", DeModel: "REDMI 13T PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1047, DeFamilyModel: "POCO F", DeModel: "POCO F6 PRO", DeMemory: "1 TB" },
    { IdObjectSmartphone: 361, DeFamilyModel: "POCO M", DeModel: "POCO M5S", DeMemory: "128 GB" },
    { IdObjectSmartphone: 385, DeFamilyModel: "MI", DeModel: "MI 12 LITE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 393, DeFamilyModel: "POCO X", DeModel: "POCO X4 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 418, DeFamilyModel: "POCO X", DeModel: "POCO X5 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 424, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 12S", DeMemory: "128 GB" },
    { IdObjectSmartphone: 445, DeFamilyModel: "REDMI", DeModel: "REDMI 12C", DeMemory: "128 GB" },
    { IdObjectSmartphone: 446, DeFamilyModel: "POCO M", DeModel: "POCO M5", DeMemory: "128 GB" },
    { IdObjectSmartphone: 448, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 11 PRO", DeMemory: "128 GB" },
    { IdObjectSmartphone: 477, DeFamilyModel: "REDMI", DeModel: "REDMI 12", DeMemory: "128 GB" },
    { IdObjectSmartphone: 491, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 12", DeMemory: "128 GB" },
    { IdObjectSmartphone: 492, DeFamilyModel: "POCO X", DeModel: "POCO X5", DeMemory: "128 GB" },
    { IdObjectSmartphone: 538, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13", DeMemory: "128 GB" },
    { IdObjectSmartphone: 974, DeFamilyModel: "POCO C", DeModel: "POCO C65", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1001, DeFamilyModel: "REDMI A", DeModel: "REDMI A3", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1091, DeFamilyModel: "REDMI", DeModel: "REDMI 13", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1107, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1147, DeFamilyModel: "POCO C", DeModel: "POCO C75", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1166, DeFamilyModel: "POCO C", DeModel: "POCO C85", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1204, DeFamilyModel: "REDMI", DeModel: "REDMI 14C", DeMemory: "128 GB" },
    { IdObjectSmartphone: 203, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 11", DeMemory: "128 GB" },
    { IdObjectSmartphone: 204, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 11S", DeMemory: "128 GB" },
    { IdObjectSmartphone: 383, DeFamilyModel: "POCO X", DeModel: "POCO X4 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 401, DeFamilyModel: "POCO F", DeModel: "POCO F4", DeMemory: "256 GB" },
    { IdObjectSmartphone: 417, DeFamilyModel: "POCO X", DeModel: "POCO X5 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 425, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 12S", DeMemory: "256 GB" },
    { IdObjectSmartphone: 444, DeFamilyModel: "POCO X", DeModel: "POCO X5", DeMemory: "256 GB" },
    { IdObjectSmartphone: 478, DeFamilyModel: "REDMI", DeModel: "REDMI 12", DeMemory: "256 GB" },
    { IdObjectSmartphone: 490, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 12 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 508, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 12", DeMemory: "256 GB" },
    { IdObjectSmartphone: 533, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 11 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 537, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13", DeMemory: "256 GB" },
    { IdObjectSmartphone: 560, DeFamilyModel: "POCO X", DeModel: "POCO X6", DeMemory: "256 GB" },
    { IdObjectSmartphone: 563, DeFamilyModel: "POCO X", DeModel: "POCO X6 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 567, DeFamilyModel: "MI", DeModel: "MI 13 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 572, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 960, DeFamilyModel: "REDMI", DeModel: "REDMI 13C", DeMemory: "256 GB" },
    { IdObjectSmartphone: 966, DeFamilyModel: "MI", DeModel: "MI 13 LITE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 971, DeFamilyModel: "POCO M", DeModel: "POCO M6 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 973, DeFamilyModel: "POCO C", DeModel: "POCO C65", DeMemory: "256 GB" },
    { IdObjectSmartphone: 979, DeFamilyModel: "POCO F", DeModel: "POCO F6", DeMemory: "256 GB" },
    { IdObjectSmartphone: 981, DeFamilyModel: "POCO F", DeModel: "POCO F5", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1041, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13 PRO PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1043, DeFamilyModel: "REDMI", DeModel: "REDMI 13T PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1045, DeFamilyModel: "MI", DeModel: "MI 13T PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1048, DeFamilyModel: "MI", DeModel: "MI 14 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1053, DeFamilyModel: "REDMI", DeModel: "REDMI 14C", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1079, DeFamilyModel: "POCO C", DeModel: "POCO C75", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1082, DeFamilyModel: "POCO X", DeModel: "POCO X7", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1087, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1088, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1106, DeFamilyModel: "POCO X", DeModel: "POCO X7 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1126, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14S", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1139, DeFamilyModel: "MI", DeModel: "MI 15", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1151, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14 PRO PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1165, DeFamilyModel: "POCO M", DeModel: "POCO M7 PRO", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1167, DeFamilyModel: "POCO M", DeModel: "POCO M7", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1124, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14 PRO PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1140, DeFamilyModel: "MI", DeModel: "MI 15", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1170, DeFamilyModel: "MI", DeModel: "MI 14T PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1171, DeFamilyModel: "POCO F", DeModel: "POCO F7", DeMemory: "512 GB" },
    { IdObjectSmartphone: 569, DeFamilyModel: "POCO X", DeModel: "POCO X6 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 577, DeFamilyModel: "REDMI", DeModel: "REDMI 13T PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 965, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13 PRO PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 972, DeFamilyModel: "POCO M", DeModel: "POCO M6 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 980, DeFamilyModel: "POCO F", DeModel: "POCO F6", DeMemory: "512 GB" },
    { IdObjectSmartphone: 996, DeFamilyModel: "MI", DeModel: "MI 14", DeMemory: "512 GB" },
    { IdObjectSmartphone: 997, DeFamilyModel: "MI", DeModel: "MI 14 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1032, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1033, DeFamilyModel: "POCO F", DeModel: "POCO F6 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1034, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 13", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1054, DeFamilyModel: "MI", DeModel: "MI 14T", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1081, DeFamilyModel: "POCO X", DeModel: "POCO X7 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1089, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1090, DeFamilyModel: "POCO X", DeModel: "POCO X7", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1095, DeFamilyModel: "POCO X", DeModel: "POCO X6", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1104, DeFamilyModel: "REDMI NOTE", DeModel: "REDMI NOTE 14 PRO", DeMemory: "512 GB" },
    { IdObjectSmartphone: 507, DeFamilyModel: "REDMI", DeModel: "REDMI 12C", DeMemory: "64 GB" }
  ];

  // Dados completos da Samsung
  const samsungDevices = [
    { IdObjectSmartphone: 535, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 ULTRA", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1060, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 5", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1061, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 4", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1078, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 ULTRA", DeMemory: "1 TB" },
    { IdObjectSmartphone: 1143, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 7", DeMemory: "1 TB" },
    { IdObjectSmartphone: 412, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 ULTRA", DeMemory: "1 TB" },
    { IdObjectSmartphone: 522, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23", DeMemory: "1 TB" },
    { IdObjectSmartphone: 368, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 4", DeMemory: "128 GB" },
    { IdObjectSmartphone: 376, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M53", DeMemory: "128 GB" },
    { IdObjectSmartphone: 377, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S9 PLUS", DeMemory: "128 GB" },
    { IdObjectSmartphone: 408, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22 PLUS", DeMemory: "128 GB" },
    { IdObjectSmartphone: 413, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A54", DeMemory: "128 GB" },
    { IdObjectSmartphone: 415, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23", DeMemory: "128 GB" },
    { IdObjectSmartphone: 450, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A34", DeMemory: "128 GB" },
    { IdObjectSmartphone: 484, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A24", DeMemory: "128 GB" },
    { IdObjectSmartphone: 494, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M34", DeMemory: "128 GB" },
    { IdObjectSmartphone: 497, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 FE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 544, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24", DeMemory: "128 GB" },
    { IdObjectSmartphone: 568, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M54", DeMemory: "128 GB" },
    { IdObjectSmartphone: 579, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A55", DeMemory: "128 GB" },
    { IdObjectSmartphone: 957, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A15", DeMemory: "128 GB" },
    { IdObjectSmartphone: 959, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A05S", DeMemory: "128 GB" },
    { IdObjectSmartphone: 976, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A35", DeMemory: "128 GB" },
    { IdObjectSmartphone: 983, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A25", DeMemory: "128 GB" },
    { IdObjectSmartphone: 989, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22 ULTRA", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1031, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A06", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1055, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A16", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1057, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M15", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1092, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 FE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1097, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A36", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1099, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1102, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A56", DeMemory: "128 GB" },
    { IdObjectSmartphone: 1145, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 7 FE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 109, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A22", DeMemory: "128 GB" },
    { IdObjectSmartphone: 110, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A23", DeMemory: "128 GB" },
    { IdObjectSmartphone: 113, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A32", DeMemory: "128 GB" },
    { IdObjectSmartphone: 114, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A33", DeMemory: "128 GB" },
    { IdObjectSmartphone: 120, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A53", DeMemory: "128 GB" },
    { IdObjectSmartphone: 126, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A73", DeMemory: "128 GB" },
    { IdObjectSmartphone: 133, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M23", DeMemory: "128 GB" },
    { IdObjectSmartphone: 147, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S20 FE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 154, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S21 FE", DeMemory: "128 GB" },
    { IdObjectSmartphone: 156, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22", DeMemory: "128 GB" },
    { IdObjectSmartphone: 148, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S20 FE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 157, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22", DeMemory: "256 GB" },
    { IdObjectSmartphone: 159, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 170, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S21 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 369, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 4", DeMemory: "256 GB" },
    { IdObjectSmartphone: 403, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 409, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 411, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 414, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A54", DeMemory: "256 GB" },
    { IdObjectSmartphone: 416, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23", DeMemory: "256 GB" },
    { IdObjectSmartphone: 449, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A32", DeMemory: "256 GB" },
    { IdObjectSmartphone: 457, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M53", DeMemory: "256 GB" },
    { IdObjectSmartphone: 485, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M54", DeMemory: "256 GB" },
    { IdObjectSmartphone: 495, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M34", DeMemory: "256 GB" },
    { IdObjectSmartphone: 498, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24", DeMemory: "256 GB" },
    { IdObjectSmartphone: 524, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 FE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 546, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 547, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 574, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A34", DeMemory: "256 GB" },
    { IdObjectSmartphone: 580, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A55", DeMemory: "256 GB" },
    { IdObjectSmartphone: 958, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A15", DeMemory: "256 GB" },
    { IdObjectSmartphone: 969, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M35", DeMemory: "256 GB" },
    { IdObjectSmartphone: 977, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A35", DeMemory: "256 GB" },
    { IdObjectSmartphone: 984, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A25", DeMemory: "256 GB" },
    { IdObjectSmartphone: 991, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 6", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1012, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 5", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1039, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 FE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1046, DeFamilyModel: "GALAXY M", DeModel: "GALAXY M55", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1056, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A16", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1062, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 4", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1074, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1096, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A26", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1098, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A56", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1100, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 PLUS", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1101, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 ULTRA", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1132, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A36", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1136, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 EDGE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1146, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 7 FE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1149, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 7", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1169, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 FE", DeMemory: "256 GB" },
    { IdObjectSmartphone: 1137, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 EDGE", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1144, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 7", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1148, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 7", DeMemory: "512 GB" },
    { IdObjectSmartphone: 158, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22", DeMemory: "512 GB" },
    { IdObjectSmartphone: 160, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S22 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 370, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 4", DeMemory: "512 GB" },
    { IdObjectSmartphone: 402, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 404, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 475, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 5", DeMemory: "512 GB" },
    { IdObjectSmartphone: 523, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S23", DeMemory: "512 GB" },
    { IdObjectSmartphone: 534, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 536, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 545, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24", DeMemory: "512 GB" },
    { IdObjectSmartphone: 992, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FLIP 6", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1040, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S24 FE", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1063, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 4", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1064, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 5", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1065, DeFamilyModel: "GALAXY Z", DeModel: "GALAXY Z FOLD 6", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1075, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1076, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 PLUS", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1077, DeFamilyModel: "GALAXY S", DeModel: "GALAXY S25 ULTRA", DeMemory: "512 GB" },
    { IdObjectSmartphone: 1174, DeFamilyModel: "GALAXY A", DeModel: "GALAXY A06", DeMemory: "64 GB" }
  ];

  const allDevices = [...appleDevices, ...samsungDevices, ...motorolaDevices, ...xiaomiDevices];
  
  // Filtra pelo modelo e extrai memórias únicas
  const filteredDevices = allDevices.filter(device => 
    device.DeModel.toUpperCase() === model.toUpperCase()
  );

  if (filteredDevices.length === 0) {
    return res.status(404).json({
      data: [],
      message: "Model not found",
      hasError: true,
      errorDataCollection: ["No devices found for this model"],
      statusCode: 404
    });
  }

  // Retorna as opções de memória disponíveis para o modelo
  const memoryOptions = filteredDevices.map(device => ({
    IdObjectSmartphone: device.IdObjectSmartphone,
    DeMemory: device.DeMemory
  }));

  res.status(200).json({
    data: memoryOptions,
    message: "OK",
    hasError: false,
    errorDataCollection: [],
    statusCode: 200
  });
}
